### ISSUE TITLE
setImageUri

### ISSUE THREAD

**Issue by liyangyang123** [Yalantis/uCrop#387] opened 2018-02-09 06:00 UTC
onFailure: setImageUri
                                                                       java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [file:///storage/emulated/0/Pictures/1517561526408.jpg]
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:113)
                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by ucdevinda123** [comment] 2018-02-20 10:49
Any fix for this ?

**Comment by ucdevinda123** [comment] 2018-02-21 09:40
In your application class  add  

if(Build.VERSION.SDK_INT>=24){
            try{
                Method m = StrictMode.class.getMethod("disableDeathOnFileUriExposure");
                m.invoke(null);
            }catch(Exception e){
                e.printStackTrace();
            }
        }

**Comment by ionutbejan** [comment] 2018-03-30 08:56
I tried the above solution, but doesn't seem to work for me.. 

This is how I create the image taken from camera, and use fileprovider to get it later
`private File createImageFile(Context context) throws IOException {
        // Create an image file name
        String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String imageFileName = "JPEG_" + timeStamp + "_";
        File storageDir = context.getFilesDir();
        Log.i(TAG, "StorageDir : " + storageDir);
        File image = File.createTempFile(
                imageFileName,  /* prefix */
                ".jpg",         /* suffix */
                storageDir      /* directory */
        );

        // Save a file: path for use with ACTION_VIEW intents
        mCurrentPhotoPath = image.getAbsolutePath();
        Log.i(TAG, "mCurrentPhotoPath : " + mCurrentPhotoPath);
        return image;
    }`

**Comment by Legementarion** [comment] 2018-04-17 15:07
@ionutbejan Hello! Please check out last version of Ucrop, bug still reproduce?

**Comment by ionutbejan** [comment] 2018-04-17 15:26
Apparently in my case it was not caused by the library itself, because I was starting UCrop inside onActivityResult(took picture from camera), and I just had to start UCrop with a small delay. Thanks anyway for your prompt response!

**Comment by Legementarion** [comment] 2018-04-17 15:33
@ionutbejan You are welcome :)

@liyangyang123  and @ucdevinda123  Could you please reproduce this bug with the last version of ucrop? Because I think it was fixed long time ago, but no one created new release build for fix.

**Comment by Legementarion** [comment] 2018-04-27 08:48
Think it fixed

**Closed by Legementarion** 2018-04-27 08:48 UTC

**Comment by ImranLoneRider** [comment] 2019-05-02 08:26
The issue can be reproduced with the latest version of uCrop.

onFailure: setImageUri
    java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [file:/storage/emulated/0/DCIM/Camera/JPEG_1556784876234_-1381901899.jpg]
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:116)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

I see the issue has been closed, but I am not able to see a solution for it.

**Comment by AndroidHelp** [comment] 2019-09-19 20:29
I am using latest version2.2.4(Lite)

onFailure: setImageUri
    java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [file:/storage/emulated/0/Android/data/com.dorna/cache/Camera/JPEG_1568924836121_749878979.jpg]
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:116)
        at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

Not fixed this issue. I am using Marshmallow
