### ISSUE TITLE
Android Q java.io.FileNotFoundException: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by Anonymous123456789123** [Yalantis/uCrop#623] opened 2020-02-19 13:41 UTC
Hi, 

I have an issue related to the android 10 or Q in which when picking an image from gallery the app crashes and mentions java.io.FileNotFoundException: open failed: EACCES (Permission denied). While it is working normally for android devices below 29. Note that the target API in gradle is 29.

Kindly your kind support is appreciated.

**Comment by Anonymous123456789123** [comment] 2020-02-21 06:27
Any update?

**Comment by florian-do** [comment] 2020-02-21 22:51
Same problem here, with the same target API

I've figure it out that  if I launch the camera intent, go back and then retry to pick up a picture from the gallery it will work perfectly

```
val takePictureIntent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)
takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, getCacheImagePath(f))
if (takePictureIntent.resolveActivity(f.requireActivity().packageManager) != null) {
    f.startActivityForResult(takePictureIntent, BFragment.REQUEST_CODE_CAMERA)
}
```

And after this it will work every time but if I uninstall / install the app it will not bug again

**Comment by goyourfly** [comment] 2020-02-23 19:19
Same problem

**Comment by Anonymous123456789123** [comment] 2020-02-24 06:28
Hi,
this requestLegacyExternalStorage="true" solve the issue but i need a solution for this because when android 11 it may not work. and note that i used a java language and not Koltin. Please if u can help me to solve the issue. Note that this code is working normally below Android 10.

 private void openImagesDocument() {
        Intent pictureIntent = new Intent(Intent.ACTION_GET_CONTENT);
        pictureIntent.setType("image/*");
        pictureIntent.addCategory(Intent.CATEGORY_OPENABLE);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            String[] mimeTypes = new String[]{"image/jpeg", "image/png"};
            pictureIntent.putExtra(Intent.EXTRA_MIME_TYPES, mimeTypes);
        }
        startActivityForResult(Intent.createChooser(pictureIntent, "Select Picture"), PICK_IMAGE_GALLERY_REQUEST_CODE);
    }

 private void openCropActivity(Uri sourceUri, Uri destinationUri) {

        UCrop.Options options = new UCrop.Options();
        options.setCircleDimmedLayer(true);


        options.setActiveWidgetColor(ContextCompat.getColor(getContext(), R.color.black));
        //options.setStatusBarColor(ContextCompat.getColor(getContext(), R.color.ToolbarcolorPrimary));
        // options.setDimmedLayerColor(ContextCompat.getColor(getContext(), R.color.ToolbarcolorPrimary));
        //options.setToolbarColor(ContextCompat.getColor(getContext(), R.color.white));
        options.setRootViewBackgroundColor(ContextCompat.getColor(getContext(), R.color.ToolbarcolorPrimary));
        options.setToolbarWidgetColor(ContextCompat.getColor(getContext(), R.color.white));
        // options.setCropFrameColor(ContextCompat.getColor(getContext(), R.color.ToolbarcolorPrimary));
        //options.setCropGridColor(ContextCompat.getColor(getContext(), R.color.ToolbarcolorPrimary));
        // options.setLogoColor(ContextCompat.getColor(getContext(), R.color.black));


        options.setToolbarColor(ContextCompat.getColor(getContext(), R.color.ToolbarcolorPrimary));
        options.setStatusBarColor(ContextCompat.getColor(getContext(), R.color.ToolbarcolorPrimary));
        options.setMaxBitmapSize(10000);
        options.setCompressionQuality(100);
        UCrop.of(sourceUri, destinationUri)
                .withOptions(options)
                .withMaxResultSize(300, 300)
                .withAspectRatio(50f, 50f)
                .start(getContext(), this);
    }

  public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
if (requestCode == PICK_IMAGE_GALLERY_REQUEST_CODE && resultCode == getActivity().RESULT_OK && data != null) {
            try {
                Uri sourceUri = data.getData();
                File file = getImageFile();
                Uri destinationUri = Uri.fromFile(file);
                openCropActivity(sourceUri, destinationUri);

            } catch (Exception e) {
                toast(getActivity(), "Please select another image");
            }
}

 private File getImageFile() throws IOException {
        File storageDir = new File(getContext().getExternalFilesDir(null), "/profile.jpg");
        currentPhotoPath = getContext().getExternalFilesDir(null) +"/profile.jpg";
        return storageDir;
    }

**Comment by florian-do** [comment] 2020-02-24 17:30
@Anonymous123456789123 
```
val pickPhoto = Intent(Intent.ACTION_GET_CONTENT)
pickPhoto.type = "image/*"
pickPhoto.addCategory(Intent.CATEGORY_OPENABLE)
pickPhoto.putExtra(Intent.EXTRA_MIME_TYPES, arrayOf("image/png", "image/jpeg"))
f.startActivityForResult(pickPhoto, BFragment.REQUEST_CODE_GALLERY)
```

sourceUri & destUri :
```
sourceUri: content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F1017/ORIGINAL/NONE/image%2Fjpeg/285607400
destinationUri: file:///storage/emulated/0/Android/data/com.xxx.xxx.local/cache/camera/resize-1582565219333.jpg
```

`onFailed: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)`

Still doesn't work, even on Android 8.1

**Comment by Anonymous123456789123** [comment] 2020-02-26 09:53
Hi 
is there any update since I'm upgrading the android studio to android-R and still crashing issue 

regards

**Comment by Anonymous123456789123** [comment] 2020-02-27 07:33
Hi
is there any update since I'm upgrading the android studio to android-R and still crashing issue in device samsung note 9 API version 11

regards

**Comment by RakeshrajRocs** [comment] 2020-02-27 08:13
Using requestLegacyExternalStorage="true" in manifest leads to AAPT error during build

**Comment by friederikewild** [comment] 2020-03-12 06:23
This might be a duplicate of https://github.com/Yalantis/uCrop/issues/598

**Comment by p1nkydev** [comment] 2020-03-18 19:50
Duplicate #598 would be fixed soon.

**Closed by p1nkydev** 2020-03-18 19:50 UTC

**Comment by t2314862168** [comment] 2020-04-17 08:19
i changed some  code and solved the problem
[BitmapCropTask.java](https://gist.github.com/t2314862168/2d6163bd91d5624ce4797973223ced62)

**Comment by Anonymous123456789123** [comment] 2020-04-20 13:35
hi,
dear can you share with me a sample android Q please
thanks
________________________________

**Comment by t2314862168** [comment] 2020-04-21 14:26
@Anonymous123456789123  emm ,  here is sample  [uCrop-2.2.4](https://github.com/t2314862168/uCrop-2.2.4) ,just clone down  and enjoy it

**Comment by jupiterwangq** [comment] 2020-04-29 10:54
I think this problem is caused by following code in BitmapLoadTask.java：
`private void processInputUri() throws NullPointerException, IOException {
        String inputUriScheme = mInputUri.getScheme();
        Log.d(TAG, "Uri scheme: " + inputUriScheme);
        if ("http".equals(inputUriScheme) || "https".equals(inputUriScheme)) {
           //....
        } else if ("content".equals(inputUriScheme)) {
            String path = getFilePath();
            if (!TextUtils.isEmpty(path) && new File(path).exists()) {
                mInputUri = Uri.fromFile(new File(path));
            } else {
                try {
                    copyFile(mInputUri, mOutputUri);
                } catch (NullPointerException | IOException e) {
                    Log.e(TAG, "Copying failed", e);
                    throw e;
                }
            }
        }`
I pass an uri with 'content' schema，but ucrop transform it to 'file' schema。

**Comment by Drjacky** [comment] 2021-05-03 13:37
@t2314862168 Could you please make a pull request and add your changes to the origin repo?

**Comment by yozhik** [comment] 2021-05-21 11:28
Here what Google write about this:
https://support.google.com/googleplay/android-developer/answer/10467955#zippy=%2Cpermitted-uses-of-the-all-files-access-permission%2Cexceptions%2Cinvalid-uses%2Calternatives-to-common-uses

We have to use: Media Store API or storage access framework to be able to run our apps on Android 11+, other ways - Google will block our accounts. Or one can write Google a message and tell why he/she can't use new API for that.

**Comment by Drjacky** [comment] 2021-05-21 14:56
Solution: https://github.com/Drjacky/ImagePicker/blob/02c6501492db230521892dffa951930a3bfa3575/imagepicker/src/main/kotlin/com/github/drjacky/imagepicker/provider/CropProvider.kt#L113-L153
