### ISSUE TITLE
return cropped image width/height in onActivityResult

### ISSUE THREAD

**Issue by suau** [Yalantis/uCrop#149] opened 2016-07-08 18:35 UTC
it would be great if the cropped ActivityResult would contain the final cropped image width and height as well, the data is already available in `BitmapCropTask` and just needs to be passed through to the BitmapCroppedCallback.

As none of the internals are exposed by this library, I think it's acceptable to change the interface of BitmapCroppedCallback.

**Comment by Mrxxy** [comment] 2016-09-07 02:49
need it, too. Because i just need the final cropped Rect,so will you support it ? Thanks.

**Comment by shliama** [comment] 2016-09-08 13:06
Thanks for the issue. I've reproduced the bug and it will be fixed in the next library update soon.

**Comment by shliama** [comment] 2016-09-08 20:54
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```

**Comment by Mrxxy** [comment] 2016-09-09 07:44
@shliama  I have download the latest version and tested,it works well.Thank you.
Here is what i add for the new api:
```java
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (resultCode == RESULT_OK && requestCode == UCrop.REQUEST_CROP) {
        int width = data.getIntExtra(UCrop.EXTRA_OUTPUT_IMAGE_WIDTH, defaultValue);
        int height = data.getIntExtra(UCrop.EXTRA_OUTPUT_IMAGE_HEIGHT, defaultValue);
    } else if (resultCode == UCrop.RESULT_ERROR) {
       Throwable cropError = UCrop.getError(data);
    }
}
```

**Comment by TeeRawk** [comment] 2017-03-13 15:34
resolved

**Closed by TeeRawk** 2017-03-13 15:34 UTC
Labels: enhancement
