### ISSUE TITLE
FileNotFoundException while choosing image from Gallery

### ISSUE THREAD

**Issue by mansoorahmadsamar** [Yalantis/uCrop#570] opened 2019-09-20 07:16 UTC
Using latest version 2.2.4

Getting imageUri via FileProvider
----------------

<external-cache-path
        name="cache"
        path="camera/" />

----------------
```
Uri destinationUri = Uri.fromFile(new File(getCacheDir(), queryName(getContentResolver(), sourceUri)));
        UCrop.Options options = new UCrop.Options();
        options.setCompressionQuality(IMAGE_COMPRESSION);
        options.setToolbarColor(ContextCompat.getColor(this, R.color.colorPrimary));
        options.setStatusBarColor(ContextCompat.getColor(this, R.color.colorPrimary));
        o
```ptions.setActiveWidgetColor(ContextCompat.getColor(this, R.color.colorPrimary));

        if (lockAspectRatio)
            options.withAspectRatio(ASPECT_RATIO_X, ASPECT_RATIO_Y);

        if (setBitmapMaxWidthHeight)
            options.withMaxResultSize(bitmapMaxWidth, bitmapMaxHeight);

        UCrop.of(sourceUri, destinationUri)
                .withOptions(options)
                .start(this);
-------------------------------

-- Exception Log

> E/TransformImageView: onFailure: setImageUri
>     java.io.FileNotFoundException: open failed: EACCES (Permission denied)
>         at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:315)
>         at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:220)
>         at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1498)
>         at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1338)
>         at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1286)
>         at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:100)
>         at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
>         at android.os.AsyncTask$3.call(AsyncTask.java:378)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:919)

**Comment by ryanhoo95** [comment] 2019-09-26 04:34
Im facing this problem as well..

compileSdkVersion and targetSdkVersion = 29
working fine on Android 9 device, but not working on Android 10 device

**Comment by clownba0t** [comment] 2019-09-30 12:11
Fairly certain this is a duplicate of #543.

**Comment by Marina24** [comment] 2020-01-24 12:12
Duplicate to #598

**Closed by Marina24** 2020-01-24 12:12 UTC
Labels: duplicate
