### ISSUE TITLE
Keeping original photo taken from camera results in blank photo.

### ISSUE THREAD

**Issue by raylee4204** [Yalantis/uCrop#142] opened 2016-07-05 22:27 UTC
When you take a photo from camera, and try tapping checkmark icon without making any changes (ratio set to original) to the photo passed to UCropActivity, it results in a blank photo.

**Comment by shliama** [comment] 2016-07-07 10:49
I cannot reproduce that.
Can you post here a snippet of you camera/ucrop flow & attach image file from camera too.

**Comment by raylee4204** [comment] 2016-07-07 14:57
`java
         // Create an image file name
        String timeStamp = DateTimeFormat.forPattern("yyyyMMdd_HHmmss").print(LocalDateTime.now());
        String imageFileName = "JPEG_" + timeStamp + "_";
        File storageDir = new File(context.getFilesDir(), "images");

        //Make sure directory exists
        if (!storageDir.exists()) {
            storageDir.mkdir();
        }

        File newFile = null;
        try {
            newFile = File.createTempFile(
                    imageFileName,  /* prefix */
                    ".jpg",         /* suffix */
                    storageDir      /* directory */
            );
        } catch (IOException e) {
            LogUtils.e("Create Image File", e.getMessage());
        }

        if (newFile == null) {
            newFile = new File(storageDir, imageFileName + ".jpg");
        }

        DisplayUtils.dispatchCameraIntent(this, newFile, REQUEST_IMAGE_CAPTURE);
`

**Comment by krokyze** [comment] 2016-07-19 22:18
This error happens not only with a photo taken from the camera. For example, in the sample app, I choose to crop a random photo, don't touch any settings, go straight to done and I get this.

<img src="https://cloud.githubusercontent.com/assets/5682176/16968392/3029a4aa-4e17-11e6-9d4c-9eaec2645643.png" width="250">

Problem is in BitmapLoadTask class when:
```java
final BitmapFactory.Options options = new BitmapFactory.Options();
options.inJustDecodeBounds = true;
BitmapFactory.decodeFileDescriptor(fileDescriptor, null, options);
if (options.outWidth == -1 || options.outHeight == -1) {
     return new BitmapWorkerResult(new IllegalArgumentException("Bounds for bitmap could not be retrieved from the Uri: [" + mInputUri + "]"));
}
```

**Comment by raylee4204** [comment] 2016-07-19 23:01
So what's the solution for this?

**Comment by shliama** [comment] 2016-07-20 08:21
I'm looking into the issue, but I have limited amount of time currently. This task has high priority and will be fixed in the next library update.

**Comment by PGMacDesign** [comment] 2016-07-28 23:15
Hey guys, ran into the same issue myself. 
Just to reiterate what others have said, it can be reproduced for any image (from camera, from gallery, or downloaded into a file) when the aspect ratio being saved is identical to the aspect ratio of the image. 
I'll fork a branch tonight and see if I can help out at all. Any particular branch I should pull from to minimize merge conflicts if I fix it?
-PGMacDesign

**Comment by PGMacDesign** [comment] 2016-07-29 16:24
An update:
Still looking through the code to try and fix it. If anyone needs an image to test with to recreate the issue, I uploaded this one to imgur which has the correct dimensions to reproduce and crash the app:
**http://i.imgur.com/mNglKRx.jpg**
--
Furthermore, when running the SampleActivity in the cloned repo, the error it is coming up with is:

07-29 09:21:58.445 13174-13174/com.yalantis.ucrop.sample E/TransformImageView: onFailure: setImageUri
                                                                               java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [file:///data/user/0/com.yalantis.ucrop.sample/cache/SampleCropImage.jpg]
                                                                                   at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:113)
                                                                                   at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by PGMacDesign** [comment] 2016-07-29 17:19
Ok! Got it fixed. It was an issue with File copying. Short version, sending the same Uri as both input and output + no cropping caused the code to try to overwrite the other and both ended up being null. This resulted in both files being returned as null and the original getting wiped out. 
[My pull ](https://github.com/Yalantis/uCrop/pull/162)request should solve that problem and shouldn't cause issues with cropped photos.

**Comment by shliama** [comment] 2016-09-08 11:25
@PGMacDesign Oh yeah, thanks for the PR -> merged it already. Will be available soon in the new update. :octocat:

**Closed by shliama** 2016-09-08 11:25 UTC
